# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Lulu Li - Academic Homepage"
description              : "Academic homepage of Dr. Lulu Li, Distinguished Researcher at National Supercomputing Center in Zhengzhou. Focuses on Multi-Agent Reinforcement Learning, Swarm Intelligence, and Sim-to-Real."
repository               : "silululi.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification :  # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   :  # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "Lulu Li (李璐璐)"
  avatar           : "images/profile.jpg" # 请确保在仓库的 images 文件夹下上传名为 profile.jpg 的个人照片
  bio              : "Distinguished Researcher @ NSCC-Zhengzhou | Master's Supervisor"
  location         : "Zhengzhou, China"
  employer         : "Zhengzhou University"
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=mqQHVaAAAAAJ&hl=en"
  email            : "lilulu1997@zzu.edu.cn"
  researchgate     :  
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "silululi"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         : 
  dblp             : 
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/
